---
- name: aws
  ansible.builtin.import_role:
    name: aws
  vars:
    dns_record_list:
    - name: "{{ private_dns }}.{{ private_domain }}"
      zone: "{{ private_domain }}"
      type: A
      value: "{{ private_ip }}"
      private: true
      ttl: 120
    tags_facts:
      private_dns: "private_dns"
      consul_cluster: "consul_cluster"
      consul_alt_domain: "consul_alt_domain"
      bootstrap_expect: "consul_bootstrap_expect"
      consul_encrypt: "consul_encrypt"


- name: Consul role
  ansible.builtin.import_role:
    name: inqwise.common.consul
  vars:
    consul_bind_addr: "{{ private_ip }}"
    consul_retry_join: '["provider=aws tag_key=consul_cluster tag_value={{ consul_cluster }}"]'
    consul_datacenter: "{{ environment_name }}-dc-1"