---
- name: aws
  ansible.builtin.import_role:
    name: aws
  vars:
    dns_record_list:
    - name: "{{ private_dns }}.{{ private_domain }}"
      zone: "{{ private_domain }}"
      type: A
      value: "{{ private_ip }}"
      private: true
      ttl: 120
    tags_facts:
      private_dns: "private_dns"
      consul_cluster: "consul_cluster"
      consul_alt_domain: "consul_alt_domain"
      consul_encrypt: "consul_encrypt"
      consul_node_name: "consul_node_name"


- name: Consul role
  ansible.builtin.import_role:
    name: inqwise.common.consul
  vars:
    consul_bind_addr: "{{ private_ip }}"
    consul_retry_join: '["provider=aws tag_key=consul_cluster tag_value={{ consul_cluster }}"]'
    consul_datacenter: "{{ environment_name }}-dc-1"
    consul_bootstrap_expect: 3

- name: Install Alloy
  include_role:
    name: alloy
  vars:
    alloy_user_groups:
      - systemd-journal
    config: |
      loki.write "local" {
        endpoint {
          url = "http://loki.{{ private_domain }}:3100/loki/api/v1/push"
        }
      }

      loki.relabel "journal" {
        forward_to = []

        rule {
          source_labels = ["__journal__systemd_unit"]
          regex         = "(consul.service|telegraf.service)"
          action        = "keep"
        }
        rule {
          source_labels = ["__journal__systemd_unit"]
          target_label  = "unit"
        }
        rule {
          source_labels = ["__journal__hostname"]
          target_label  = "instance"
        }
      }

      loki.source.journal "read" {
        forward_to = [
          loki.write.local.receiver,
        ]
        relabel_rules = loki.relabel.journal.rules
        labels = {
          "job" = "integrations/node_exporter",
          "app" = "consul",
        }
      }
  tags: always